zenoss/zenoss.metric.consumer

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/TsdbMetricsQueue.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/impl/MetricsQueue.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/impl/OpenTsdbWriter.java
metric-consumer-app/src/test/java/org/zenoss/app/consumer/metric/impl/OpenTsdbWriterTest.java
pom.xml

Do not merge yet. Need to have a non-SNAPSHOT version of metric-tsdb released and used as a dependency.

ZEN-15966 - Fix NPE, connection pool leak, and "in flight" leak. Detect errors while sending metrics to OpenTsdb, rather than losing them.

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/impl/OpenTsdbWriter.java

Please review branch feature/ZEN-17749

---

metric-consumer-app/src/main/etc/configuration.yaml
metric-consumer-app/src/main/etc/metric-consumer-app_supervisor.conf

http://dropwizard.github.io/dropwizard/0.6.2/manual/core.html#configuration-defaults details requestLog config file syntax.

Fixes ZEN-18412, ZEN-18418

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebSocket.java

See pull request #66. I'm just being defensive here since we're porting this to the support branch.

ZEN-18489 - Add defensive null-check

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/impl/OpenTsdbWriter.java

cherry-pick pull-request #70
(committed by "zendev port cherry-pick")

Fixes ZEN-20307

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebResource.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebSocket.java

Added additional error logging on public web socket and api methods to make it easier to track down this problem the next time it occurs.
ZEN-19869

InvocationTargetException in MetricConsumer, requiring consumer restart

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/impl/OpenTsdbWriter.java

cherry-pick pull-request #70
(committed by "zendev port cherry-pick")

Fixes ZEN-20306

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebResource.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebSocket.java

Please review branch feature/ZEN-20374

---

metric-consumer-app/src/main/etc/configuration.yaml
metric-consumer-app/src/main/java/org/zenoss/app/consumer/ConsumerAppConfiguration.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebResource.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebSocket.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/Utils.java
metric-consumer-app/src/test/java/org/zenoss/app/consumer/metric/remote/UtilsTest.java

This is a small part of the fix for ZEN-17550, but could be useful for
other applications.

ZEN-17550: Support tag whitelist prefixes

---

pom.xml

cherry-pick pull-request #76
(committed by "zendev port cherry-pick")

Fixes ZEN-23199

---

metric-consumer-app/pom.xml
metric-data/pom.xml
pom.xml

Also fixed a unittest by way of updating metric-tsdb

Update findbugs to 3.0.1

---

metric-consumer-app/src/test/java/org/zenoss/app/consumer/metric/remote/MetricWebResourceTest.java
metric-consumer-app/src/test/java/org/zenoss/app/consumer/metric/remote/MetricWebSocketTest.java
pom.xml

Please review branch feature/ZEN-23806

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/StatusResource.java

Please review branch feature/ZEN-23867

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/StatusResource.java

Reverts zenoss/zenoss.metric.consumer#81

Revert "Please review branch feature/ZEN-23867"

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/StatusResource.java

To prevent the media type errors

Cast boolean to string before sending to client

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/impl/MetricServicePoster.java
metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/MetricWebSocket.java

ZEN-24455 Store Tenant ID with websocket session

---

metric-consumer-app/src/main/java/org/zenoss/app/consumer/metric/remote/StatusResource.java

This is port from : https://github.com/zenoss/zenoss.metric.consumer/pull/75

ZEN-23867: add new healthchecks

---

pom.xml

Pull request created by zendev port.
Fixes ZEN-24708.

Please review branch feature/ZEN-24708

---

metric-consumer-app/src/main/bin/metric-consumer-app.sh

[JIRA&DEMO](https://jira.zenoss.com/browse/ZEN-30158)

ZEN-30158: Add new option to process once it OOM

---

pom.xml

resolving ZEN-32777 and ZEN-33171

ZEN-32777 bump jackson to 2.11.3 and junit to 4.13.1
